### ISSUE TITLE
Feature request: Display a top 10 list of famous programmers on the results page

### ISSUE THREAD

**Issue by Reinoptland** [karinhogenbirk/famousProgrammers#2]
# What

One of the cool features of this app is that we can determine which programmers are most easily recognised (or famous). The quiz feature all ready implements this as it counts the "votes" for each programmer when the answer is correct or a negative vote if the answer is wrong.

But on the results page, the programmers are not listed yet (there is a placeholder though!) 

![Screenshot 2022-10-26 at 13 38 27](https://user-images.githubusercontent.com/20372832/198017012-77f4d712-856a-4219-9f10-406cf769a34b.png)

Consider implementing this by: 

- [x] Making GET /programmers return a sorted list of programmers by amount of votes
- [x] Fetching from this endpoint on the results page
- [x] Displaying the results (looping, with document.getElement etc.)

**Comment by karinhogenbirk** [comment]
done:)
