### ISSUE TITLE
Feature request: responsive styling

### ISSUE THREAD

**Issue by Reinoptland** [karinhogenbirk/famousProgrammers#3]
# What

The current design is implemented for a mobile screen, but the content does not quite fit on a mobile phone. On tablet and desktop there is a lot of empty space. We can center the content, or even create a "desktop" layout with elements having more space. 

Here are some quick and dirty suggestions: 

Mobile currently:
![Screenshot 2022-10-26 at 13 43 07](https://user-images.githubusercontent.com/20372832/198018090-5c87c9a6-4fbf-473d-a5c8-e73cc633ae37.png)
Could be like: 
![Screenshot 2022-10-26 at 13 43 26](https://user-images.githubusercontent.com/20372832/198018103-d8a4535a-beba-4517-bfc4-4f7a3d2405db.png)
Tablet - centering
![Screenshot 2022-10-26 at 13 43 56](https://user-images.githubusercontent.com/20372832/198018115-918cd213-c4ec-44c4-b88c-a36a670d3d95.png)
Desktop layout idea 
![Screenshot 2022-10-26 at 13 44 52](https://user-images.githubusercontent.com/20372832/198018122-97e917a6-c406-4cf5-be9f-585ffa455ade.png)

**Comment by karinhogenbirk** [comment]
done!
