### ISSUE TITLE
Deploying v1

### ISSUE THREAD

**Issue by Reinoptland** [karinhogenbirk/famousProgrammers#4]
# What

The first version of the app is (almost) ready to be beta tested. We can deploy without a database to play the quiz and get some feedback from the first users. What we need to do

- [x] Create a new service on render.com and link this repo
- [x] Configure how to start the app (`npm start`)

Should be a piece of cake! (knock on wood)

**Comment by karinhogenbirk** [comment]
it's done! 
https://famous-programmers.onrender.com
