### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by Reinoptland** [karinhogenbirk/famousProgrammers#8]
# Why 

We want to have an admin page where a maintainer can add, remove or update programmers and projects
This way the data stays "fresh", new and important projects are created all the time!

## What

- Want to have a page `/admin` which is just an HTML file
- When you go to this page, we want to check wether you are logged in
- If you are not logged, we send you to the login page
- If you are logged in, we display your username in the top right 

## How

- [x] When we arrive at the admin page, we send a GET request to /auth/me, with a Bearer token in the Authorization header
```js
const token = GET_FROM_STORAGE_HERE

fetch('URL_GOES_HERE', { 
   method: 'get', 
   headers: {
     'Authorization': `Bearer ${token}`, 
     'Content-Type': 'application/json'
   }, 
 });
```

- [x] In the backend we create the a `GET /auth/me` endpoint, when you make a request to this endpoint: 
   - [x] We check _if_ you sent a authorization header at all, if not -> Bad request
   - [x] We check _if_ the authorization header contains `Bearer` inside the string, if not -> Bad request
   - [x] We then split the Authorization header on a space: " ",  "Bearer eyhaldafjsfdkasdlasdlasdflasdas", the second part should be the token
   - [x] We then verify that we created the token, and that it is valid using `jwt.verify`
![Screenshot 2022-11-24 at 09 49 47](https://user-images.githubusercontent.com/20372832/203735909-430c7575-0b2d-489b-b90f-e51e5afda20b.png)
   - [x] If the token is not valid, this will throw an error, so you need a `try catch` around this, when not valid, catch error and return a `401 Unauthorized` response with an error message
   - [x] If the token is valid, get the id from the token (the payload, should be in `decoded`) and find the user in the database according to the id
   - [x] Return 200 and send back the email and other info (but not the password hash!)
- [x] In the frontend when we get a succes response display the email of the user in the top right (or somewhere) to let them know they are logged in 
- In the frontend if we get a 401 Unauthorized
  - [x] Delete the token from local storage
  - [x] Send the user to the login page (you can use `window.location` to do this) 

That's it!

**Comment by karinhogenbirk** [comment]
Done :)
