### ISSUE TITLE
Adding a new programmer

### ISSUE THREAD

**Issue by Reinoptland** [karinhogenbirk/famousProgrammers#9]
# What

It's nice to have the ability to add a new programmer + project to the database using a a form on the admin page

## Why

- We scraped the programmer data from wikipedia, but new and important projects are created an worked on all the time
- We only want people with admin access to be able to add new programmers

## How

- Create a form on the admin page to add a new programmer 
- Send the token as an auth header when you send a request
- Use the auth middleware to check wether the user is logged in before handling the post request

## Anything else?

- Validate the input in the body (programmer + project) 
- The name of the programmer should be unique (we don't want duplicates right?)
- You can validate the input in the frontend as well, perhaps using [this](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation)
- You are AWESOME!

**Comment by karinhogenbirk** [comment]
Done
